Repository Team-Hankki/hankki-server, pull requests merged in 2024-08, with the labels that each got.

#133 [fix] 족보 상세조회 정렬 fix
  src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteFinder.java
  src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteQueryService.java
  src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteGetResponse.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
  src/main/java/org/hankki/hankkiserver/domain/favorite/repository/FavoriteRepository.java
  src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
Labels: fix, api

#149 [refac] 좋아요 로직 예외처리 추가
  src/main/java/org/hankki/hankkiserver/api/auth/service/UserFinder.java
  src/main/java/org/hankki/hankkiserver/api/store/service/HeartCommandService.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
Labels: refactoring

#155 [feat] 식당 등록 API
  src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
  src/main/java/org/hankki/hankkiserver/api/universitystore/controller/UniversityStoreController.java
  src/main/java/org/hankki/hankkiserver/api/universitystore/controller/request/UniviersityStoreCreateRequest.java
  src/main/java/org/hankki/hankkiserver/api/universitystore/service/UniversityStoreCommandService.java
  src/main/java/org/hankki/hankkiserver/api/universitystore/service/command/UniversityStorePostCommand.java
Labels: api

#153 [feat] 식당 제보 검증 api
  src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreQueryService.java
  src/main/java/org/hankki/hankkiserver/api/store/service/command/StoreValidationCommand.java
  src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreDuplicateValidationResponse.java
  src/main/java/org/hankki/hankkiserver/common/code/StoreErrorCode.java
  src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
Labels: api

#157 [fix] 기본 이미지 정책 변경에 따른 로직 수정
  src/main/java/org/hankki/hankkiserver/api/advice/GlobalExceptionHandler.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java
  src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreResponse.java
  src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreThumbnailResponse.java
  src/main/java/org/hankki/hankkiserver/common/code/StoreImageErrorCode.java
  src/main/java/org/hankki/hankkiserver/common/exception/BadGatewayException.java
Labels: api

#158 [feat] 족보 제목 중복 예외 처리
  src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
  src/main/java/org/hankki/hankkiserver/api/favorite/controller/request/FavoritePostRequest.java
  src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteCommandService.java
  src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteFinder.java
  src/main/java/org/hankki/hankkiserver/common/code/FavoriteErrorCode.java
  src/main/java/org/hankki/hankkiserver/domain/favorite/repository/FavoriteRepository.java
Labels: api

#165 [fix] 내가 제보한 식당에서 이미지 없으면 안가져오는 문제 fix
  src/main/java/org/hankki/hankkiserver/domain/report/repository/ReportRepository.java
Labels: fix, api

#147 [refac] 직접 쿼리 삭제 및 쿼리 개선
  src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java
  src/main/java/org/hankki/hankkiserver/api/auth/service/UserFinder.java
  src/main/java/org/hankki/hankkiserver/api/auth/service/UserInfoDeleter.java
  src/main/java/org/hankki/hankkiserver/domain/user/model/User.java
  src/main/java/org/hankki/hankkiserver/domain/user/model/UserInfo.java
  src/main/java/org/hankki/hankkiserver/domain/user/repository/UserInfoRepository.java
  src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleOAuthProvider.java
Labels: refactoring

#169 [fix] 식당 제보 validation 검증 조건 추가
  src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
  src/main/java/org/hankki/hankkiserver/api/store/controller/request/StoreDuplicateValidationRequest.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreQueryService.java
  src/main/java/org/hankki/hankkiserver/api/store/service/command/StoreValidationCommand.java
  src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
Labels: fix, api

#172 [fix] 사용자 대학교 미설정 가능하도록 변경
  src/main/java/org/hankki/hankkiserver/api/user/controller/request/UserUniversityPostRequest.java
  src/main/java/org/hankki/hankkiserver/api/user/service/response/UserUniversityFindResponse.java
Labels: fix

#174 [fix] 대학교 조회시 name기준 오름차순 정렬하도록 변경
  src/main/java/org/hankki/hankkiserver/api/university/controller/UniversityController.java
  src/main/java/org/hankki/hankkiserver/api/university/service/UniversityFinder.java
  src/main/java/org/hankki/hankkiserver/api/university/service/UniversityQueryService.java
  src/main/java/org/hankki/hankkiserver/domain/university/repository/UniversityRepository.java
Labels: bug

#176 [fix] 유저 대학교 설정 api 검증 조건 변경
  src/main/java/org/hankki/hankkiserver/api/user/controller/request/UserUniversityPostRequest.java
Labels: bug

#167 [feat] 족보 상세보기에서 식당 정렬순 족보에 추가한 순으로 변경
  src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteQueryService.java
  src/main/java/org/hankki/hankkiserver/api/favoritestore/service/FavoriteStoreFinder.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
  src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
Labels: feature, api

#178 [fix] 식당 생성시 예외처리 조건 수정
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
  src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
Labels: bug

#183 [fix] image_url 컬럼 타입 TEXT로 변경
  src/main/java/org/hankki/hankkiserver/domain/store/model/StoreImage.java
Labels: bug

#186 [fix] cd 오류 수정
  src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java
Labels: bug

#187 [feat] exception handler에 예외 추가
  src/main/java/org/hankki/hankkiserver/api/advice/GlobalExceptionHandler.java
  src/main/java/org/hankki/hankkiserver/common/code/BusinessErrorCode.java
Labels: enhancement
